packages:
  - apps/*
  - packages/*
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  '@scarf/scarf': true
  esbuild: true
  onnxruntime-node: false
  prisma: true
  protobufjs: false
  sharp: true
